### ISSUE TITLE
[Regression] Link's Awakening DX Menu Sound Crackle

### ISSUE THREAD

**Issue by Awakened0** [LIJI32/SameBoy#161]
In the latest libretro build, there is a sort of stuttery crackle in the BGM whenever you open the menu (Start). It happens when transitioning through some of the menus too, like from title screen to save select. It doesn't happen in an older build I have from Jan 19th.

**Comment by Awakened0** [comment]
Just to update, when the libretro mirror updated to 3ee2c648996c6eb3a2fb32113b984215f54b7b02 I checked the buildbot build and still experience this. Haven't noticed any other crackling in other places in LADX or other games, so I don't think it's performance related.

**Comment by Awakened0** [comment]
Testing a bit more, I found a little crackle when entering and leaving the pause menu in Kirby's Dream Land 2 as well that's in the new build but not the January one. It's more subtle than in LADX. Seems like it's mostly fade style screen transitions where it happens. But it doesn't happen when opening LADX's map or any of the menus in Oracle of Seasons.

**Comment by RokkumanX** [comment]
Great findings @Awakened0 

I hear what you hear too but I'm not sure if Gambatte or bgb suffers from this as well? Never really thought of it much when I played the game on those but in SameBoy it's definitely more apparent.

**Comment by LIJI32** [comment]
Are you referring to the few pops that can be heard when you open the menu in certain areas, and that crackling sound you get when the music fades out? If so, these are not bugs – these can be heard when you play the game on actual hardware. If that's not what you mean, can you please attach an audio recording affected by this bug?

**Comment by Awakened0** [comment]
This doesn't sound like the usual GB pops to me. Comparing the older core with the latest one, it sounds like the BGM transitions have a sort of stuttery crackle, whereas they're smooth in the old one. Here's a recording, January core first, latest core from the buildbot second:

[LADX Old Vs. New.zip](https://github.com/LIJI32/SameBoy/files/3292574/LADX.Old.Vs.New.zip)

**Comment by LIJI32** [comment]
Do you have actual commit hashes of the versions compared? The only related diff between those dates is in the buffer copy function, and it doesn't explain many of the differences I see between the recordings.

**Comment by Awakened0** [comment]
The Jan build has this hash: 3cc57ba
Latest is: f1a75fc

**Comment by LIJI32** [comment]
Since I suspect the audio buffer copying code, and I've wanted to replace it for quite a while, I rewrote it and redesigned its API, and updated the relevant frontends (libretro wrapper, Cocoa, SDL). Specifically on the libretro port, it leaves most of the work to RetroArch now, which should improve quality and latency. Can you check if anything improved after last commit?

**Comment by Awakened0** [comment]
Built it and the issue hasn't changed, unfortunately.

**Comment by LIJI32** [comment]
I'm extremely confused, the APU related differences between those two revisions are:

1. The buffer copying function
2. AGB mixing emulation (I assume you're testing on CGB mode and not AGB?)
3. A few optimization hints for the compiler.

If it's not 1, I'm not sure what could have caused it. Since it won't reproduce on my machine, maybe you can try and `git bisect` it so I can know which commit changed it?

**Comment by Awakened0** [comment]
I was thinking about doing that, but I can't figure out how to checkout an old commit and also apply the libretro buildbot patch to get it built. Normally I just copy the prebuilt bootroms and makefile from the libretro buildbot branch and build using an msys2 environment.

I have no idea how to install dependencies in that to compile directly from this repo. Tried adding BOOTROMS_DIR=./prebuilt with the prebuilt folder under msys64/home/<username> and no luck there either.

**Comment by LIJI32** [comment]
What error are you getting? With BOOTROMS_DIR defined the only unusual requirement for compilation on Windows should be `hexdump`.

**Comment by funbars** [comment]
@Awakened0 
Some x64 builds. Can't test myself now.
[https://github.com/LIJI32/SameBoy/commit/9d0aadb83fa0d63fb6810f05ff6089686cf82db4](https://ci.appveyor.com/api/buildjobs/mafuh4dulx4tqq0m/artifacts/build%2Fbin%2Fsameboy_libretro.dll)

(will keep updating post)

**Comment by Awakened0** [comment]
@funbars 
https://github.com/LIJI32/SameBoy/commit/9d0aadb83fa0d63fb6810f05ff6089686cf82db4 - Bad
https://github.com/LIJI32/SameBoy/commit/b3939e8fdcec9882fc57a4e4fbe3722860c3d1ee - Bad
https://github.com/LIJI32/SameBoy/commit/b6e92dc8a74c850df3c5af49310e6c018d6c6707 - Bad
https://github.com/LIJI32/SameBoy/commit/5ead9d49f4eac01e2c58de5ac0efe5195358db6b - Good

@LIJI32 
Same error as if I hadn't defined the bootroms dir. I tried a bunch of relative paths, but I'm not sure exactly which folder is supposed to be root (home, sameboy, libretro, ?). And I was just using this dir from the libretro repo: https://github.com/libretro/SameBoy/tree/buildbot/BootROMs/prebuilt

**Comment by funbars** [comment]
@Awakened0 
Great! Last ones
https://github.com/LIJI32/SameBoy/commit/9d0aadb83fa0d63fb6810f05ff6089686cf82db4 = bad
[https://github.com/LIJI32/SameBoy/commit/42ef41182d68dfeafe26838d3a13c91eb52bd07b](https://ci.appveyor.com/api/buildjobs/01fkbav7l65vnww5/artifacts/build%2Fbin%2Fsameboy_libretro.dll)
https://github.com/LIJI32/SameBoy/commit/dde06e7cae094859d7e0501bb824fe1e04379b61 = wip
https://github.com/LIJI32/SameBoy/commit/5ead9d49f4eac01e2c58de5ac0efe5195358db6b = good

**Comment by Awakened0** [comment]
42ef411 - Good
dde06e7 - Good

**Comment by LIJI32** [comment]
I think I see what's going on here. The Game Boy, being able to turn its LCD screen off, does not actually guarantee a stable 59.7 FPS. This thing happens when you open the menu and close it, for example. If I understand correctly, the libretro API does not allow a non constant FPS, so in such cases SameBoy reports a frame that is shorter than usual, which has, as expected, a fewer number of samples. RetroArch simply takes this frame's length, stretches it to the usual size together with the audio, plays the two together. The change that caused this issue slightly altered how specific cases of "irregular" frames are reported to the frontend. In the Cocoa and SDL frontend the video and audio aren't coupled at all which is why I couldn't reproduce it. Now, this effect can easily be mitigated by making the libretro frontend "mimic" the behavior before that change, but this still won't be a perfect/correct solution without proper variable FPS in libretro/RetroArch. Also, is it possible to make RetroArch sync to audio instead of video? This should fix the problem completely.

**Comment by Awakened0** [comment]
Hmm, but I'm using "Sync to Exact Content Framerate" under Settings, Throttle with a Gsync display. Thought that would mitigate this sort of issue. The description label under it says "No deviation from core requested timing".  I think with that enabled it syncs to audio instead of video, but @Tatsuya79 would know more about it.

**Comment by Tatsuya79** [comment]
"Exact sync" just follows info->timing.fps that the core sends. That's pretty basic.

I have constant crackling when I use SGB1 while SGB2 is OK if that can help to figure the issue.
For popping when bringing up the menu, I noticed that activating the high pass filter got rid of that (while the core is active, not at start).

**Comment by LIJI32** [comment]
Yup, following `info->timing.fps` is exactly what shouldn't happen in this case, as the frame rate momentarily changes to something a higher, so this option is better off for SameBoy. This also explains crackling in SGB1, as SGB1 runs at a different frame rate yet I didn't updated `info->timing.fps` accordingly. SGB2 (for the Game Boy perspective, I don't emulate the SFC's frame rate) runs at the same rate so it's not affected.

Also, the high pass filter should really ever be disabled, at the very least it should be set to "Preserve Waveforms", as otherwise the audio will always have DC offset, which not only triggers pops on FPS drops, might also interfere audio playing from other applications. I should probably make it the default setting in the core.

**Comment by LIJI32** [comment]
The last commit should make audio on libretro as good as it was before the regression on GB, CGB, GBA and SGB2. I still have to fix the SGB issue but that's a different problem. It's not a proper solution, but it should be equivalent to Gambatte,

**Comment by Awakened0** [comment]
Yep, tested LADX and a few other games and everything sounds good. Thanks everyone!

**Comment by nfp0** [comment]
I'm having this exact same issue on RetroArch.
On Link's Awakening, while opening the start menu, or when transitioning between the startup cutscene -> startscreen -> savefile select, I always get very slight crackling on the audio.

I have tested this on Windows and on Manjaro. Both exhibit the same problem as described on the original post.
This does not happen on Gambatte.

**Comment by Awakened0** [comment]
I only hear what should be the hardware accurate pops. Using a Win64 build I made from this repo from commit 2a034d4ebe79613b88921d35396f8228b708c671

**Comment by nfp0** [comment]
@Awakened0 Are the pops reproducible every time? Does Gambatte have these same pops?
What I hear is a bit irregular, and is not present at all in other GB cores.

**Comment by nfp0** [comment]
It is specially noticeable in the transition between the BIOS and the cutscene, and between the cutscene and the start screen.

**Comment by Awakened0** [comment]
> @Awakened0 Are the pops reproducible every time? Does Gambatte have these same pops?
What I hear is a bit irregular, and is not present at all in other GB cores.

It's pretty consistent on my end. Here's what it sounds like for me:


https://user-images.githubusercontent.com/4565863/165411756-abd86434-f74c-4151-9dc3-0b29acb43a8e.mp4

**Comment by Awakened0** [comment]
> It is specially noticeable in the transition between the BIOS and the cutscene, and between the cutscene and the start screen.

Looking at my opening post in this thread, that could be a regression. There's definitely a little sound stutter in those transitions. I don't keep old builds of the core around anymore to compare though.

**Comment by nfp0** [comment]
> It's pretty consistent on my end. Here's what it sounds like for me:

Yeah, that's exactly how it sounds on my end too. That roughness before the waves appear and before the start screen appears is what I'm talking about.

I've checked on the GearBoy, TGB Dual, mGBA and Gambatte cores, and none of them have this behavior. SameBoy is the only one.
If this is more accurate, I'm all for it. But I want to make sure that is how real hardware sounded and if this needs to be fixed or not.

**Comment by Awakened0** [comment]
Getting the same audio behavior in the [Libretro buildbot version](https://buildbot.libretro.com/nightly/windows/x86_64/latest/sameboy_libretro.dll.zip) which is built from [their downstream repo](https://github.com/libretro/SameBoy). That repo hasn't been updated since December, so if this is a regression it's older than that.

**Comment by nfp0** [comment]
Yeah, same behavior from the Libretro buildbot version here. That's where I noticed this, actually.

I tried building https://github.com/LIJI32/SameBoy/commit/431f1f8199166578b051651e6ff1c0cbd48766ab, from when things were apparently fixed, but I am getting build errors.

> error: BootROMs/agb_boot.asm(2) -> BootROMs/cgb_boot.asm(512):
    syntax error, unexpected newline

**Comment by nfp0** [comment]
I have confirmed this only happens on the libretro core. I tried the standalone SameBoy from AUR and the crackling does not happen there.
Should I open a new issue on this repo, or on the libretro fork?

**Comment by Awakened0** [comment]
I can reopen this and add a libretro tag.

**Comment by LIJI32** [comment]
Isn't this solved by #444?

**Comment by Awakened0** [comment]
My previous build should be based on that commit, but I just did a fresh one from 18126994ff35c880677d51728aa5f995219592e1 and it still has those little stutters. It only seems to happen on certain screen transitions; in game audio generally seems fine. Mario Land and Kirby's Dream Land also have a less noticeable stutter when transitioning to some new screens or levels. I haven't tested stand alone yet, but assume they aren't there from nfp0's comment.

**Comment by nfp0** [comment]
> Isn't this solved by #444?

@LIJI32  I've built from master and the issue is still there.

**Comment by nfp0** [comment]
Has there been any progress in fixing this issue?
If not, I can open an issue on the libretro side to see if anyone familiar with libretro can fix it.

**Comment by Awakened0** [comment]
Don't see any improvement with a fresh build.

It might get some more eyes on the problem with a new issue opened over there, so it's probably worth it.

**Comment by LIJI32** [comment]
Opening a libretro issue could help. Basically [my original fix](https://github.com/LIJI32/SameBoy/issues/161#issuecomment-503296260) was essentially a workaround, as the libretro API can't handle cores with variable frame rates correct, and I'm assuming a recent change in how I handle extra frames in LCD on/off scenarios caused a regression again. I'm not sure how RA handles audio stretching and such in these kinds of scenarios, but I'm guessing somebody from libretro could offer some better way to fix or handle this.

**Comment by Awakened0** [comment]
Ok, I opened an issue on the libretro repo: https://github.com/libretro/SameBoy/issues/85

**Comment by nfp0** [comment]
I've posted this downstream on libretro, but I'll also post it here in case it helps with anything:

I've recorded a bit of gameplay on Link's Awakening DX with Mangohud showing disturbances in frame pacing when the GameBoy changes screens in the game. The crackling is audible too, both on the menus and when entering and exiting the house.

This audio issue does not seem to be happening on standalone SameBoy.

https://user-images.githubusercontent.com/11202422/194921501-e1317a30-efd7-4df4-ac36-e4b56d8a5b15.mp4

**Comment by nfp0** [comment]
I've tested this recently and I cannot reproduce the audio crackling anymore.
The only crackling remaining is the same present on the standalone version and on other emulatores and GB cores, so I assume it's accurate.

Can anyone verify if it's also fixed for them? I'm testing on RetroArch 1.15.0

**Comment by Awakened0** [comment]
Tested with a fresh build of the core and RetroArch. I still get the same crackles in Link's Awakening DX when going through the intro screens. I tried the buildbot's older core too (0.15.4) with the same result. On Windows using D3D11 or vulkan with xaudio.

**Comment by nfp0** [comment]
I've tried with both the original Link's Awakening and the DX version and none produce the crackling anymore in the intro screen for me.
I haven't changed anything in my configuration other than updating the OS and RetroArch. I don't know what fixed it.

I'm on Linux using Vulkan for video and the Pulse driver for audio. What could've fixed it?

**Comment by nfp0** [comment]
Listening again, the crackling is still there after all.
I've also noticed it sometimes occurs when pressing Start on Super Mario Land's start screen to begin the game.

**Comment by Awakened0** [comment]
Yeah, checking after just building the core again I don't hear any improvement with Link's Awakening. I can hear the slight crackle when a stage starts after selecting it from the map screen in SMB Deluxe too.

**Comment by nfp0** [comment]
Could this be related to the fact that this core outputs audio at 384000 Hz? No other core I use outputs anything this high.
Gambatte outputs at 32768 Hz, for example.

> I can hear the slight crackle when a stage starts after selecting it from the map screen in SMB Deluxe too.

Same here. Even though it's not consistent. Seems random.
But it's also inconsistent on Link's Awakening.

**Comment by nfp0** [comment]
I've made quite an interesting find.
This crackling only manifests when I play on a 60hz screen. I cannot hear it when I play on my 180hz monitor. Just moving the window between monitors and resetting Zelda Link's Awakening DX makes the issue reproduce every time.

How to reproduce:
1) Load Link's Awakening DX on SameBoy core on 60hz monitor
2) Listen to crackle right after the GBC boot logo
3) Move window to 180hz monitor
4) Press 'h' to reset the game
5) The crackle is gone

I've tried this more than 10 times, moving the window between monitors and it always reproduces consistently.
Can I help debug this?

**Comment by Awakened0** [comment]
I exclusively use a single screen running at 120hz. That is with Gsync active, which will use VRR to go down to ~60hz to match the game's FPS, at least in fullscreen. The crackling is there in fullscreen with Gsync at ~60hz or in a window locked to 120hz.

**Comment by nfp0** [comment]
Has there been any progress in finding out what causes this?

@LIJI32 I am not sure if this was mentioned before, but this is happening also on standalone SameBoy, so it's not related to Libretro.

I did some tests on the latest commit and the problem persists. It crackles on transitions when played on my 60hz screen but the sound is clean on my 180hz one.
Could this be related to how SameBoy tries to Vsync to 60 Hz screens VS other Hz?

**Comment by LIJI32** [comment]
The fact that is happens on both standalone and Libretro is weirdly contradictory. SameBoy on Libretro does not care about Vsync and such, it delegates it to the libretro frontend, so if both the standalone and Libretro versions are affected, it means that both RetroArch itself *and* the SDL version of SameBoy have the exact same bug where the screen refresh rate affects the audio.

Can you please try the following?
1. Try version 1.0.1, both standalone and libretro. This version improves audio rendering, and also changes the way audio is handled in the libretro version, let me know if it had any effect.
2. In the standalone version, try using the built-in audio recording feature from the menu. Audio recording completely bypasses any system audio APIs, so it shouldn't be affected by Vsync and such. Can you confirm there are no artifacts when recording audio this way?

**Comment by nfp0** [comment]
@LIJI32 I tested what you asked:

1) I've compiled the master branch for standalone and the libretro branch for the Libretro core. Both exhibit the same problem.

2) Interesting, indeed on the audio recording there is no crackling at all! Does this fact, plus the fact that the behavior changes depending on the monitor's Hz mean it's then related to Vsync?

After this I also tested with the alsa and alsathread audio drivers on RetroArch (pulse is the default) and the problem remains the same.
I also noticed that the core now reports 2097152 Hz of sample rate. Is this normal? It's the only core I've seen reporting such a high number.

If I can help with anything else to root out this issue please advise.

**Comment by LIJI32** [comment]
OK, so first this confirms this isn't a problem with the core but probably two, similar but unrelated bugs with the frontend – one with the standalone SDL frontend and one with RetroArch. Can you check if any other cores in RetroArch are affected? 

As for the 2MHz sample rate – this is intentional and a recent change in 1.0.1. The Game Boy itself indeed outputs audio in 2MHz, but before version 1.0 SameBoy did not allow outputting audio directly in this frequency, it required downsampling to some lower sample rate. Due to a limitation in the libretro API, the core could not know what's the user's configured sample rate, so before version 1.0.1 SameBoy downsampled the 2MHz audio to an intermediate 256KHz rate, and then RetroArch resampled it once again to whatever rate the user has selected. This was a bit inefficient and slightly degraded audio quality, so now that the core supports direct 2MHz audio output, downsampling is only done by RetroArch.

**Comment by LIJI32** [comment]
Another interesting thing to try – since you’re running on Linux, you have the option to use the OpenAL audio driver in SameBoy’s SDL frontend. Can you try and see if it has an positive or negative effect on this? Note that you will need to restart SameBoy for this to take effect.

**Comment by Awakened0** [comment]
Here's how it sounds for me in a recent nightly RetroArch on Windows with the latest nightly core (1.0.1 9916fbd):
XAudio:
https://github.com/user-attachments/assets/88f36342-53f5-456b-b4d4-eaec26228e46

WASAPI Shared Mode:
https://github.com/user-attachments/assets/ac510e99-fc92-47b9-b809-8f48dc1ee902

Standalone Windows Sameboy 1.0.1 using XAudio just has the normal sounding brief pops.

**Comment by Awakened0** [comment]
I also just tested on Android and wasn't getting the issue there. Both devices have 120hz screens and I have vsync enabled on both. Comparing settings, I figured I'd try turning off "Sync to Exact Content Framerate" on the Windows machine, since it's off on the phone. Turning that off does fix the audio issue for me.

I use "Sync to Exact Content Framerate" with all the other cores I use without audio problems like this. There is a slight "warbling" effect with WASAPI, but XAudio is fine. I generally want to leave that on since I get smoother frame pacing without having to switch to 60hz (which adds display lag.)

**Comment by nfp0** [comment]
@LIJI32

> Can you check if any other cores in RetroArch are affected?

I use 5 other cores and I have not noticed anything like this.
In particular, for Game Boy, the Gambatte core does not suffer from this problem.

> As for the 2MHz sample rate...

Ah yes, I understand now! Thank you for the explanation.

> Another interesting thing to try – since you’re running on Linux, you have the option to use the OpenAL audio driver in SameBoy’s SDL frontend

That helps a lot, yes! Using the OpenAL audio has reduced the crackling greatly. Perhaps even eliminated it.
What can we learn out of this to fix it on RetroArch and SDL?
Does this mean RetroArch is using SDL? It's not available in the audio drivers menu there.



@Awakened0 

> I figured I'd try turning off "Sync to Exact Content Framerate" on the Windows machine, since it's off on the phone. Turning that off does fix the audio issue for me.

When I enable that setting on my VRR monitor (the 180hz one where the sound is clean) the VRR kicks in and the monitor's frequency is effectively reduced to approximately 60hz, to match the Game Boy output, and then the crackling starts.
On the 60Hz monitor changing that setting makes no difference in the crackling.

By the way, the kind of sound distortion I get is similar to the ones you recorded, but yours is even more prevalent.

**Comment by nfp0** [comment]
@Awakened0 

> I use "Sync to Exact Content Framerate" with all the other cores I use without audio problems like this. There is a slight "warbling" effect with WASAPI, but XAudio is fine. I generally want to leave that on since I get smoother frame pacing without having to switch to 60hz (which adds display lag.)

OFF-TOPIC:
To have proper Vsync working for 60hz cores on a 120hz monitor o you need to increase "VSync Swap Interval" to 2, and disable "Sync to Exact Content Framerate".

That guarantees perfect frame pacing. Not sure how frame pacing works with "Sync to Exact Content Framerate".

**Comment by Awakened0** [comment]
> To have proper Vsync working for 60hz cores on a 120hz monitor o you need to increase "VSync Swap Interval" to 2, and disable "Sync to Exact Content Framerate".

That's how I used to do it when I had a non-VRR 120hz display. But I had some issues with swap interval 2 last time I tried it. On my phone it causes some cores to sound crackle, where they're fine with 1. I forget what issues I had on the desktop. But ultimately I've found gsync plus sync to exact content framerate to have the least amount of problems across different cores and video APIs.
